# Generated by Django 6.0.6 on 2026-06-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='codigo',
            field=models.CharField(default='000000', max_length=6, verbose_name='Codigo'),
        ),
    ]
