run:
	python manage.py runserver


makemigartions:
	python manage.py makemigrations


migrate:
	python manage.py migrate


shell:
	python manage.py shell_plus


superuser:
	python manage.py createsuperuser